-- Draft fix generated by supabase-rls-audit. REVIEW before applying: owner-scoped policies assume each row belongs to the signed-in user.
-- If other users must read some rows (public profiles, shared items), add a narrower SELECT policy or a view for those fields.

alter view "public"."member_directory" set (security_invoker = on);

-- public.orders: RLS was off (CRITICAL); rows belong to user_id
alter table "public"."orders" enable row level security;
drop policy if exists "orders_select_own" on "public"."orders";
create policy "orders_select_own" on "public"."orders" for select to authenticated using ((select auth.uid()) = "user_id");
drop policy if exists "orders_insert_own" on "public"."orders";
create policy "orders_insert_own" on "public"."orders" for insert to authenticated with check ((select auth.uid()) = "user_id");
drop policy if exists "orders_update_own" on "public"."orders";
create policy "orders_update_own" on "public"."orders" for update to authenticated using ((select auth.uid()) = "user_id") with check ((select auth.uid()) = "user_id");
drop policy if exists "orders_delete_own" on "public"."orders";
create policy "orders_delete_own" on "public"."orders" for delete to authenticated using ((select auth.uid()) = "user_id");
revoke all on "public"."orders" from anon;  -- remove this line if logged-out visitors must read the table

-- public.profiles: RLS was off (CRITICAL); rows belong to id
alter table "public"."profiles" enable row level security;
drop policy if exists "profiles_select_own" on "public"."profiles";
create policy "profiles_select_own" on "public"."profiles" for select to authenticated using ((select auth.uid()) = "id");
drop policy if exists "profiles_insert_own" on "public"."profiles";
create policy "profiles_insert_own" on "public"."profiles" for insert to authenticated with check ((select auth.uid()) = "id");
drop policy if exists "profiles_update_own" on "public"."profiles";
create policy "profiles_update_own" on "public"."profiles" for update to authenticated using ((select auth.uid()) = "id") with check ((select auth.uid()) = "id");
drop policy if exists "profiles_delete_own" on "public"."profiles";
create policy "profiles_delete_own" on "public"."profiles" for delete to authenticated using ((select auth.uid()) = "id");
revoke all on "public"."profiles" from anon;  -- remove this line if logged-out visitors must read the table

-- public.audit_log: RLS was off (HIGH); rows belong to user_id
alter table "public"."audit_log" enable row level security;
drop policy if exists "audit_log_select_own" on "public"."audit_log";
create policy "audit_log_select_own" on "public"."audit_log" for select to authenticated using ((select auth.uid()) = "user_id");
drop policy if exists "audit_log_insert_own" on "public"."audit_log";
create policy "audit_log_insert_own" on "public"."audit_log" for insert to authenticated with check ((select auth.uid()) = "user_id");
drop policy if exists "audit_log_update_own" on "public"."audit_log";
create policy "audit_log_update_own" on "public"."audit_log" for update to authenticated using ((select auth.uid()) = "user_id") with check ((select auth.uid()) = "user_id");
drop policy if exists "audit_log_delete_own" on "public"."audit_log";
create policy "audit_log_delete_own" on "public"."audit_log" for delete to authenticated using ((select auth.uid()) = "user_id");
revoke all on "public"."audit_log" from anon;  -- remove this line if logged-out visitors must read the table

-- public.audit_log: replace always-true policy "log insert"
drop policy if exists "log insert" on "public"."audit_log";
alter table "public"."audit_log" enable row level security;
drop policy if exists "audit_log_insert_own" on "public"."audit_log";
create policy "audit_log_insert_own" on "public"."audit_log" for insert to authenticated with check ((select auth.uid()) = "user_id");

alter view "public"."note_counts" set (security_invoker = on);

-- public.notes: replace always-true policy "Anyone can do anything"
drop policy if exists "Anyone can do anything" on "public"."notes";
alter table "public"."notes" enable row level security;
drop policy if exists "notes_select_own" on "public"."notes";
create policy "notes_select_own" on "public"."notes" for select to authenticated using ((select auth.uid()) = "user_id");
drop policy if exists "notes_insert_own" on "public"."notes";
create policy "notes_insert_own" on "public"."notes" for insert to authenticated with check ((select auth.uid()) = "user_id");
drop policy if exists "notes_update_own" on "public"."notes";
create policy "notes_update_own" on "public"."notes" for update to authenticated using ((select auth.uid()) = "user_id") with check ((select auth.uid()) = "user_id");
drop policy if exists "notes_delete_own" on "public"."notes";
create policy "notes_delete_own" on "public"."notes" for delete to authenticated using ((select auth.uid()) = "user_id");

alter function "public"."promote_to_admin"(target uuid) set search_path = public;  -- check the body uses schema-qualified names; '' is stricter

-- public.workspace_settings: policy "admins manage settings" trusts user_metadata. Needs a human decision (see report).

alter policy "admins manage settings" on "public"."workspace_settings" using (((((select auth.jwt()) -> 'user_metadata'::text) ->> 'role'::text) = 'admin'::text)) with check (((((select auth.jwt()) -> 'user_metadata'::text) ->> 'role'::text) = 'admin'::text));
