import { qi, qname } from "./introspect.js";

const short = (s) => s.slice(0, 50);

function ownerPolicies(schema, table, owner, cmds = ["select", "insert", "update", "delete"]) {
  const T = qname(schema, table);
  const O = qi(owner);
  const own = `(select auth.uid()) = ${O}`;
  const lines = [`alter table ${T} enable row level security;`];
  const mk = (cmd, body) => {
    const name = qi(short(`${table}_${cmd}_own`));
    lines.push(`drop policy if exists ${name} on ${T};`, `create policy ${name} on ${T} for ${cmd} to authenticated ${body};`);
  };
  if (cmds.includes("select")) mk("select", `using (${own})`);
  if (cmds.includes("insert")) mk("insert", `with check (${own})`);
  if (cmds.includes("update")) mk("update", `using (${own}) with check (${own})`);
  if (cmds.includes("delete")) mk("delete", `using (${own})`);
  return lines;
}

function wrapAuthCalls(expr) {
  const tokens = [];
  let s = expr.replace(/\(\s*SELECT\s+auth\.(uid|jwt|role|email)\(\)\s+AS\s+\w+\s*\)/gi, (m) => { tokens.push(m); return `\u0001${tokens.length - 1}\u0001`; });
  s = s.replace(/auth\.(uid|jwt|role|email)\(\)/gi, (m) => `(select ${m})`);
  return s.replace(/\u0001(\d+)\u0001/g, (_, i) => tokens[Number(i)]);
}

// Produces a DRAFT migration. Owner-scoped fixes are mechanical; anything that needs a product decision is listed under `manual`.
export function generateFix(findings, model) {
  const sql = [];
  const manual = [];
  const done = new Set();
  const once = (key, fn) => { if (!done.has(key)) { done.add(key); fn(); } };

  sql.push("-- Draft fix generated by supabase-rls-audit. REVIEW before applying: owner-scoped policies assume each row belongs to the signed-in user.", "-- If other users must read some rows (public profiles, shared items), add a narrower SELECT policy or a view for those fields.", "");

  for (const f of findings) {
    const [schema, table] = f.object.split(".");
    const t = model.tables[f.object];
    switch (f.rule) {
      case "RLS-DISABLED":
        once(`rls:${f.object}`, () => {
          if (t?.owner) {
            sql.push(`-- ${f.object}: RLS was off (${f.severity}); rows belong to ${t.owner}`);
            sql.push(...ownerPolicies(schema, table, t.owner));
            if (t.anyAnon) sql.push(`revoke all on ${qname(schema, table)} from anon;  -- remove this line if logged-out visitors must read the table`);
            sql.push("");
          } else {
            sql.push(`-- ${f.object}: RLS was off (${f.severity}) and no owner column was found. Enabling RLS locks the API until you add a policy.`, `alter table ${qname(schema, table)} enable row level security;`, `-- Decide, then uncomment ONE:`, `-- create policy "${short(table + "_read_all")}" on ${qname(schema, table)} for select to anon, authenticated using (true);  -- genuinely public data only`, `-- create policy "${short(table + "_admin_only")}" on ${qname(schema, table)} for all to authenticated using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');`, "");
            manual.push({ object: f.object, rule: f.rule, note: "No owner column detected: choose who may read/write (public read-only, admin-only, or membership-based)." });
          }
        });
        break;
      case "POLICY-NO-RLS":
        once(`rls:${f.object}`, () => sql.push(`alter table ${qname(schema, table)} enable row level security;`, ""));
        break;
      case "POLICY-ALWAYS-TRUE":
        if (t?.owner && f.severity !== "INFO" && f.severity !== "LOW") {
          once(`pol:${f.object}:${f.evidence.policy}`, () => {
            const cmds = f.evidence.cmd === "ALL" || !f.evidence.cmd ? ["select", "insert", "update", "delete"] : [f.evidence.cmd.toLowerCase()];
            sql.push(`-- ${f.object}: replace always-true policy "${f.evidence.policy}"`, `drop policy if exists ${qi(f.evidence.policy)} on ${qname(schema, table)};`, ...ownerPolicies(schema, table, t.owner, cmds), "");
          });
        } else if (f.severity !== "INFO" && f.severity !== "LOW") {
          manual.push({ object: f.object, rule: f.rule, note: `Policy "${f.evidence.policy}" is always true and no owner column was found: decide the real condition.` });
        }
        break;
      case "USER-METADATA-POLICY":
        manual.push({ object: f.object, rule: f.rule, note: `Rewrite policy "${f.evidence.policy}" to use app_metadata (server-controlled) or a roles table: e.g. (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'.` });
        sql.push(`-- ${f.object}: policy "${f.evidence.policy}" trusts user_metadata. Needs a human decision (see report).`, "");
        break;
      case "POLICY-NO-IDENTITY":
        manual.push({ object: f.object, rule: f.rule, note: `Policy "${f.evidence.policy}" does not look at the caller: bind it to auth.uid() or a role check.` });
        break;
      case "VIEW-DEFINER":
      case "AUTH-USERS-EXPOSED":
        once(`view:${f.object}`, () => sql.push(`alter view ${qname(schema, table)} set (security_invoker = on);`, ""));
        break;
      case "MATVIEW-IN-API":
        once(`mv:${f.object}`, () => sql.push(`revoke all on ${qname(schema, table)} from anon, authenticated;`, ""));
        break;
      case "DEFINER-FUNCTION":
        if (!f.evidence.search_path_fixed) once(`fn:${f.object}`, () => {
          const m = /^([^.]+)\.(.+)\((.*)\)$/.exec(f.object);
          if (m) sql.push(`alter function ${qi(m[1])}.${qi(m[2])}(${m[3]}) set search_path = public;  -- check the body uses schema-qualified names; '' is stricter`, "");
        });
        if (f.evidence.callable_by?.includes("anon")) manual.push({ object: f.object, rule: f.rule, note: "Callable by logged-out users: confirm that is intended, otherwise `revoke execute ... from anon, public`." });
        break;
      case "STORAGE-BROAD-WRITE":
        manual.push({ object: f.object, rule: f.rule, note: `Storage policy "${f.evidence.policy}": restrict by folder, e.g. (storage.foldername(name))[1] = (select auth.uid())::text.` });
        break;
      default:
        break;
    }
  }

  // performance: wrap auth calls so they run once per query
  const initFindings = findings.filter((f) => f.rule === "AUTH-INITPLAN");
  for (const f of initFindings) {
    const [schema, table] = f.object.split(".");
    for (const name of f.evidence.policies) {
      const p = model.policies.find((x) => x.schema === schema && x.table === table && x.name === name);
      if (!p || (p.alwaysTrue && p.isWrite)) continue;
      const parts = [];
      if (p.qual) parts.push(`using (${wrapAuthCalls(p.qual)})`);
      if (p.with_check) parts.push(`with check (${wrapAuthCalls(p.with_check)})`);
      sql.push(`alter policy ${qi(name)} on ${qname(schema, table)} ${parts.join(" ")};`);
    }
  }
  return { sql: sql.join("\n") + "\n", manual };
}
